import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import * as Sharing from "expo-sharing";
import { File, Paths } from "expo-file-system";
import { supabase } from "@/src/lib/supabase";
import { peso } from "@/src/lib/format";
import { Text, TextInput } from "./AppTypography";

type Expense={id:string;expense_date:string;description:string;category:string;amount:number;payment_method:string;notes:string|null;created_at:string};
const C={ink:"#182530",muted:"#626A73",navy:"#142C47",ruby:"#65243A",border:"#E1E5E8",soft:"#F6F7F8",white:"#FFF"};
const categories=["Shop","Product","Personal","Transport","Bills","Other"];
const payments=[["cash","Cash"],["gcash","GCash"],["bank","Bank"],["other","Other"]] as const;
const today=()=>new Date().toLocaleDateString("en-CA");
const display=(value:string)=>{const [y,m,d]=value.slice(0,10).split("-");return d&&m&&y?`${d}-${m}-${y}`:value};
const parse=(value:string)=>{const m=value.match(/^(\d{2})-(\d{2})-(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:null};
const csv=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;

export function ExpensesScreen({businessId,locationId}:{businessId:string;locationId:string}){
 const [rows,setRows]=useState<Expense[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Expense|null>(null),[formOpen,setFormOpen]=useState(false);
 const [date,setDate]=useState(display(today())),[description,setDescription]=useState(""),[category,setCategory]=useState("Shop"),[amount,setAmount]=useState(""),[payment,setPayment]=useState("cash"),[notes,setNotes]=useState(""),[filter,setFilter]=useState("All");
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from("expenses").select("*").eq("location_id",locationId).order("expense_date",{ascending:false}).order("created_at",{ascending:false});if(error)Alert.alert("Expenses not loaded",error.message);setRows((data??[]) as Expense[]);setLoading(false)},[locationId]);
 useEffect(()=>{void load()},[load]);
 const total=useMemo(()=>rows.reduce((n,x)=>n+Number(x.amount),0),[rows]);
 const open=(item?:Expense)=>{setEditing(item??null);setDate(display(item?.expense_date??today()));setDescription(item?.description??"");setCategory(item?.category??"Shop");setAmount(item?String(item.amount):"");setPayment(item?.payment_method??"cash");setNotes(item?.notes??"");setFormOpen(true)};
 const save=async()=>{const iso=parse(date),value=Number(amount);if(!iso)return Alert.alert("Check date","Enter the date as DD-MM-YYYY.");if(!description.trim())return Alert.alert("What was bought?","Enter what the money was spent on.");if(!Number.isFinite(value)||value<=0)return Alert.alert("Check amount","Expense amount must be more than ₱0.");const payload={business_id:businessId,location_id:locationId,expense_date:iso,description:description.trim(),category,amount:value,payment_method:payment,notes:notes.trim()||null};const result=editing?await supabase.from("expenses").update(payload).eq("id",editing.id):await supabase.from("expenses").insert({...payload,created_by:(await supabase.auth.getUser()).data.user!.id});if(result.error)return Alert.alert("Expense not saved",result.error.message);setFormOpen(false);await load()};
 const remove=(item:Expense)=>Alert.alert("Remove this expense?",`${item.description} · ${peso(Number(item.amount))}`,[{text:"Keep",style:"cancel"},{text:"Remove",style:"destructive",onPress:async()=>{const {error}=await supabase.from("expenses").delete().eq("id",item.id);if(error)Alert.alert("Expense not removed",error.message);else await load()}}]);
 const exportCsv=async()=>{const data=[["Date","What was spent on","Category","Amount","Payment method","Notes"],...rows.map(x=>[display(x.expense_date),x.description,x.category,x.amount,x.payment_method,x.notes??""])].map(r=>r.map(csv).join(",")).join("\n");const name=`mik-expenses-${display(today())}.csv`;if(Platform.OS==="web"){const url=URL.createObjectURL(new Blob(["\uFEFF"+data],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}else{const file=new File(Paths.cache,name);file.create();file.write("\uFEFF"+data);await Sharing.shareAsync(file.uri)}};
 if(formOpen)return <ScrollView contentContainerStyle={s.page}><Pressable style={s.back} onPress={()=>setFormOpen(false)}><Ionicons name="arrow-back" size={20} color={C.ink}/><Text style={s.backText}>Expenses</Text></Pressable><Text style={s.title}>{editing?"Edit expense":"Add expense"}</Text><Text style={s.help}>Record what was paid, when it was paid and how.</Text><Field label="Date spent · Required" value={date} onChangeText={setDate} placeholder="DD-MM-YYYY"/><Field label="What was it spent on? · Required" value={description} onChangeText={setDescription} placeholder="Example: Market stall rental"/><Text style={s.label}>Category</Text><View style={s.choices}>{categories.map(x=><Choice key={x} label={x} active={category===x} onPress={()=>setCategory(x)}/>)}</View><Field label="Amount · Required" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="₱0"/><Text style={s.label}>Paid using</Text><View style={s.choices}>{payments.map(([id,label])=><Choice key={id} label={label} active={payment===id} onPress={()=>setPayment(id)}/>)}</View><Field label="Remarks · Optional" value={notes} onChangeText={setNotes} placeholder="Add a short note"/><Pressable style={s.primary} onPress={save}><Text style={s.primaryText}>Save expense</Text></Pressable></ScrollView>;
 return <ScrollView contentContainerStyle={s.page}><View style={s.heading}><View><Text style={s.title}>Expenses</Text><Text style={s.help}>A clear record of money spent by the shop.</Text></View><Pressable style={s.primarySmall} onPress={()=>open()}><Ionicons name="add" size={19} color={C.white}/><Text style={s.primaryText}>Add expense</Text></Pressable></View><View style={s.total}><Text style={s.totalLabel}>TOTAL RECORDED EXPENSES</Text><Text style={s.totalValue}>{peso(total)}</Text></View><View style={s.filterChoices}>{["All",...categories].map(x=><Choice key={x} label={x} active={filter===x} onPress={()=>setFilter(x)}/>)}</View>{loading?<Text style={s.empty}>Loading expenses…</Text>:rows.filter(x=>filter==="All"||x.category===filter).length?rows.filter(x=>filter==="All"||x.category===filter).map(item=><View key={item.id} style={s.row}><View style={{flex:1,minWidth:0}}><Text style={s.rowTitle}>{item.description}</Text><Text style={s.rowMeta}>{display(item.expense_date)} · {item.category} · {item.payment_method.toUpperCase()}</Text>{item.notes?<Text style={s.notes}>{item.notes}</Text>:null}</View><View style={s.rowRight}><Text style={s.amount}>{peso(Number(item.amount))}</Text><View style={s.actions}><Pressable onPress={()=>open(item)}><Text style={s.edit}>Edit</Text></Pressable><Pressable onPress={()=>remove(item)}><Text style={s.remove}>Remove</Text></Pressable></View></View></View>):<Text style={s.empty}>No expenses in this category.</Text>}<Pressable style={s.export} onPress={exportCsv}><Ionicons name="download-outline" size={19} color={C.navy}/><Text style={s.exportText}>Export expenses for Excel</Text></Pressable></ScrollView>;
}
function Field(props:any){return <View><Text style={s.label}>{props.label}</Text><TextInput {...props} style={s.input} placeholderTextColor="#8A9199"/></View>}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable style={[s.choice,active&&s.choiceOn]} onPress={onPress}><Text style={[s.choiceText,active&&s.choiceTextOn]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{paddingTop:18,paddingBottom:100},heading:{flexDirection:"row",flexWrap:"wrap",alignItems:"center",justifyContent:"space-between",gap:14},title:{fontSize:28,lineHeight:35,fontWeight:"700",color:C.ink},help:{marginTop:4,fontSize:15,lineHeight:22,color:C.muted},primarySmall:{minHeight:46,paddingHorizontal:15,flexDirection:"row",alignItems:"center",gap:7,borderRadius:10,backgroundColor:C.navy},primary:{minHeight:56,marginTop:24,alignItems:"center",justifyContent:"center",borderRadius:10,backgroundColor:C.navy},primaryText:{color:C.white,fontSize:14,fontWeight:"700"},total:{marginTop:18,padding:18,borderRadius:12,backgroundColor:C.soft,borderWidth:1,borderColor:C.border},totalLabel:{fontSize:11,fontWeight:"700",letterSpacing:1.2,color:C.muted},totalValue:{marginTop:6,fontSize:29,fontWeight:"700",color:C.ink},filterChoices:{paddingVertical:14,flexDirection:"row",flexWrap:"wrap",gap:8},row:{paddingVertical:16,flexDirection:"row",gap:14,borderBottomWidth:1,borderBottomColor:C.border},rowTitle:{fontSize:16,lineHeight:21,fontWeight:"700",color:C.ink},rowMeta:{marginTop:5,fontSize:12,lineHeight:18,color:C.muted},notes:{marginTop:5,fontSize:13,lineHeight:18,color:C.ink},rowRight:{alignItems:"flex-end"},amount:{fontSize:17,fontWeight:"700",color:C.ruby},actions:{marginTop:10,flexDirection:"row",gap:14},edit:{fontSize:13,fontWeight:"700",color:C.navy},remove:{fontSize:13,fontWeight:"700",color:C.ruby},empty:{paddingVertical:28,textAlign:"center",color:C.muted},export:{minHeight:52,marginTop:18,borderWidth:1,borderColor:C.navy,borderRadius:10,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},exportText:{fontSize:14,fontWeight:"700",color:C.navy},back:{minHeight:44,flexDirection:"row",alignItems:"center",gap:8},backText:{fontSize:15,fontWeight:"700",color:C.ink},label:{marginTop:17,marginBottom:7,fontSize:13,fontWeight:"700",color:C.ink},input:{minHeight:54,paddingHorizontal:14,borderWidth:1,borderColor:C.border,borderRadius:10,backgroundColor:C.white,fontSize:16,color:C.ink},choices:{flexDirection:"row",flexWrap:"wrap",gap:8},choice:{minHeight:42,paddingHorizontal:13,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:C.border,borderRadius:9,backgroundColor:C.white},choiceOn:{borderColor:C.navy,backgroundColor:C.navy},choiceText:{fontSize:13,color:C.ink},choiceTextOn:{fontWeight:"700",color:C.white}});
