import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { peso } from "@/src/lib/format";
const C={ink:"#101318",muted:"#626A73",production:"#65243A",soft:"#F8F1F3",border:"#E8D8DE",white:"#FFF",green:"#264A3B"};
const number=(value:string)=>Math.max(0,Number(value)||0);
export function PrintPriceCalculator({onBack}:{onBack:()=>void}){
 const [grams,setGrams]=useState("");const [hours,setHours]=useState("");const [spoolPrice,setSpoolPrice]=useState("900");const [spoolWeight,setSpoolWeight]=useState("1000");const [machineHour,setMachineHour]=useState("10");const [labour,setLabour]=useState("");const [extra,setExtra]=useState("");const [profit,setProfit]=useState("40");
 const result=useMemo(()=>{const material=number(grams)/Math.max(1,number(spoolWeight))*number(spoolPrice);const machine=number(hours)*number(machineHour);const cost=material+machine+number(labour)+number(extra);const suggested=cost*(1+number(profit)/100);return{material,machine,cost,suggested};},[grams,hours,spoolPrice,spoolWeight,machineHour,labour,extra,profit]);
 return <ScrollView contentContainerStyle={s.page}><Pressable style={s.back} onPress={onBack}><Ionicons name="arrow-back" size={22} color={C.ink}/><Text style={s.backText}>Price calculator</Text></Pressable><Text style={s.title}>What should I charge?</Text><Text style={s.help}>Use the estimates from Bambu Studio. Mik suggests a price, but you can still choose the final selling price.</Text><View style={s.guide}><View style={s.number}><Text style={s.numberText}>1</Text></View><View style={{flex:1}}><Text style={s.guideTitle}>Enter the print</Text><Text style={s.guideText}>Only filament grams and print hours are needed. The other values can keep their defaults.</Text></View></View><Field label="Filament used in grams · Required" value={grams} set={setGrams} placeholder="Example: 85"/><Field label="Print time in hours · Required" value={hours} set={setHours} placeholder="Example: 4.5"/><View style={s.guide}><View style={s.number}><Text style={s.numberText}>2</Text></View><View style={{flex:1}}><Text style={s.guideTitle}>Check the shop costs</Text><Text style={s.guideText}>Change these only when the shop pays a different amount.</Text></View></View><Field label="Price of one spool" value={spoolPrice} set={setSpoolPrice}/><Field label="Spool weight in grams" value={spoolWeight} set={setSpoolWeight}/><Field label="Printer cost per hour" value={machineHour} set={setMachineHour}/><Field label="Labour or finishing cost · Optional" value={labour} set={setLabour}/><Field label="Packaging or other cost · Optional" value={extra} set={setExtra}/><Field label="Profit to add (%)" value={profit} set={setProfit}/><View style={s.result}><Text style={s.resultKicker}>MIK PRICE GUIDE</Text><Text style={s.suggested}>{peso(result.suggested)}</Text><Text style={s.resultHelp}>Suggested selling price</Text><View style={s.breakdown}><Line label="Filament" value={result.material}/><Line label="Printer time" value={result.machine}/><Line label="Estimated total cost" value={result.cost} strong/></View><Text style={s.disclaimer}>This is a guide, not an automatic selling price. Custom design difficulty and market value may change what you charge.</Text></View></ScrollView>;
}
function Field({label,value,set,placeholder="0"}:{label:string;value:string;set:(v:string)=>void;placeholder?:string}){return <View><Text style={s.label}>{label}</Text><TextInput style={s.input} value={value} onChangeText={set} keyboardType="decimal-pad" placeholder={placeholder}/></View>}
function Line({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <View style={s.line}><Text style={[s.lineText,strong&&s.strong]}>{label}</Text><Text style={[s.lineText,strong&&s.strong]}>{peso(value)}</Text></View>}
const s=StyleSheet.create({page:{paddingTop:18,paddingBottom:40},back:{minHeight:48,flexDirection:"row",alignItems:"center",gap:8},backText:{color:C.ink,fontSize:20,fontWeight:"700"},title:{marginTop:9,color:C.ink,fontSize:30,fontWeight:"700",letterSpacing:-.7},help:{marginTop:6,color:C.muted,fontSize:14,lineHeight:21},guide:{marginTop:22,paddingTop:18,flexDirection:"row",gap:11,borderTopWidth:1,borderTopColor:C.border},number:{width:31,height:31,alignItems:"center",justifyContent:"center",borderRadius:16,backgroundColor:C.production},numberText:{color:C.white,fontWeight:"800"},guideTitle:{color:C.ink,fontSize:17,fontWeight:"700"},guideText:{marginTop:3,color:C.muted,fontSize:13,lineHeight:19},label:{marginTop:16,marginBottom:6,color:C.ink,fontSize:13,fontWeight:"700"},input:{minHeight:54,paddingHorizontal:14,borderWidth:1,borderColor:C.border,borderRadius:10,backgroundColor:C.white,color:C.ink,fontSize:17},result:{marginTop:25,padding:22,borderRadius:17,backgroundColor:C.production},resultKicker:{color:"#E7CBD4",fontSize:10,fontWeight:"800",letterSpacing:1.5},suggested:{marginTop:9,color:C.white,fontSize:40,fontWeight:"800"},resultHelp:{color:"#F0DDE3",fontSize:13},breakdown:{marginTop:18,paddingTop:12,borderTopWidth:1,borderTopColor:"rgba(255,255,255,.2)"},line:{paddingVertical:5,flexDirection:"row",justifyContent:"space-between"},lineText:{color:"#F4E8EC",fontSize:13},strong:{color:C.white,fontWeight:"800"},disclaimer:{marginTop:15,color:"#E8D8DE",fontSize:11,lineHeight:17}});
