import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { supabase } from "@/src/lib/supabase";

type PrinterStatus = "working" | "needs_attention" | "under_repair" | "retired";
type Printer = { id:string; name:string; model:string; status:PrinterStatus; notes:string|null; updated_at:string };

const STATUSES: Array<{id:PrinterStatus;label:string;short:string;color:string;soft:string;icon:keyof typeof Ionicons.glyphMap}> = [
  {id:"working",label:"Working",short:"Working",color:"#087A38",soft:"#EAF6EF",icon:"checkmark-circle"},
  {id:"needs_attention",label:"Needs attention",short:"Attention",color:"#8A5D12",soft:"#FBF4E6",icon:"alert-circle"},
  {id:"under_repair",label:"Under repair",short:"Repair",color:"#9B2C3F",soft:"#FAECEF",icon:"construct"},
  {id:"retired",label:"Retired",short:"Retired",color:"#606870",soft:"#F0F1F2",icon:"archive"},
];
const MODELS=["A1 mini","A1","P1S","X1 Carbon","H2D","Other"];
const statusInfo=(status:PrinterStatus)=>STATUSES.find(x=>x.id===status)!;

export function PrintersScreen({businessId,locationId,onBack}:{businessId:string;locationId:string;onBack:()=>void}) {
  const {width}=useWindowDimensions();
  const [printers,setPrinters]=useState<Printer[]>([]);
  const [loading,setLoading]=useState(true);
  const [editing,setEditing]=useState<Printer|"new"|null>(null);
  const [name,setName]=useState(""); const [model,setModel]=useState("P1S");
  const [status,setStatus]=useState<PrinterStatus>("working"); const [notes,setNotes]=useState("");
  const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from("printers").select("id,name,model,status,notes,updated_at").eq("business_id",businessId).order("status").order("name");if(error)Alert.alert("Printers not loaded",error.message);setPrinters((data??[]) as Printer[]);setLoading(false);},[businessId]);
  useEffect(()=>{void load();},[load]);
  const counts=useMemo(()=>Object.fromEntries(STATUSES.map(s=>[s.id,printers.filter(p=>p.status===s.id).length])) as Record<PrinterStatus,number>,[printers]);
  const active=printers.filter(p=>p.status!=="retired").length;
  const openNew=()=>{setEditing("new");setName(`Printer ${String(active+1).padStart(2,"0")}`);setModel("P1S");setStatus("working");setNotes("");};
  const openEdit=(p:Printer)=>{setEditing(p);setName(p.name);setModel(p.model);setStatus(p.status);setNotes(p.notes??"");};
  const save=async()=>{if(!name.trim()||!model.trim())return Alert.alert("Name and model needed","Give the printer a simple name and choose its model.");setSaving(true);const payload={business_id:businessId,location_id:locationId,name:name.trim(),model:model.trim(),status,notes:notes.trim()||null,updated_at:new Date().toISOString()};const result=editing==="new"?await supabase.from("printers").insert(payload):await supabase.from("printers").update(payload).eq("id",editing!.id);setSaving(false);if(result.error)return Alert.alert("Printer not saved",result.error.message);setEditing(null);await load();};
  const remove=()=>{if(!editing||editing==="new")return;Alert.alert("Remove this printer?","It will be permanently removed from the fleet list.",[{text:"Keep printer",style:"cancel"},{text:"Remove",style:"destructive",onPress:async()=>{const {error}=await supabase.from("printers").delete().eq("id",editing.id);if(error)return Alert.alert("Printer not removed",error.message);setEditing(null);await load();}}]);};
  if(editing)return <ScrollView contentContainerStyle={s.page}>
    <Pressable style={s.back} onPress={()=>setEditing(null)}><Ionicons name="arrow-back" size={22} color="#111820"/><Text style={s.backText}>{editing==="new"?"Add printer":"Edit printer"}</Text></Pressable>
    <View style={s.formCard}><Text style={s.formTitle}>{editing==="new"?"Add to your fleet":"Printer details"}</Text><Text style={s.help}>Keep it simple. You can change the status whenever something happens.</Text>
      <Text style={s.label}>Printer name</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Example: Printer 01"/>
      <Text style={s.label}>Model</Text><TextInput style={s.input} value={model} onChangeText={setModel} placeholder="Search or type printer model"/><View style={[s.wrap,{marginTop:8}]}>{MODELS.filter(x=>x!=="Other").map(x=><Pressable key={x} style={[s.choice,model===x&&s.choiceOn]} onPress={()=>setModel(x)}><Text style={[s.choiceText,model===x&&s.choiceTextOn]}>{x}</Text></Pressable>)}</View>
      <Text style={s.label}>Current status</Text><View style={s.statusChoices}>{STATUSES.map(x=><Pressable key={x.id} style={[s.statusChoice,{backgroundColor:x.soft,borderColor:status===x.id?x.color:"transparent"}]} onPress={()=>setStatus(x.id)}><Ionicons name={x.icon} size={23} color={x.color}/><Text style={[s.statusChoiceText,{color:x.color}]}>{x.label}</Text>{status===x.id?<Ionicons name="checkmark" size={19} color={x.color}/>:null}</Pressable>)}</View>
      <Text style={s.label}>Note</Text><TextInput style={[s.input,s.notes]} value={notes} onChangeText={setNotes} placeholder="Example: Nozzle needs replacing" multiline/>
      <Pressable style={[s.save,saving&&{opacity:.6}]} onPress={()=>void save()} disabled={saving}><Ionicons name="checkmark" size={21} color="#FFF"/><Text style={s.saveText}>{saving?"Saving…":"Save printer"}</Text></Pressable>
      {editing!=="new"?<Pressable style={s.remove} onPress={remove}><Text style={s.removeText}>Remove printer</Text></Pressable>:null}
    </View>
  </ScrollView>;
  const columns=width>=1000?3:width>=680?2:1; const cardWidth=columns===3?"32.3%":columns===2?"49%":"100%";
  return <ScrollView contentContainerStyle={s.page}>
    <View style={s.heading}><View style={{flex:1}}><Pressable style={s.back} onPress={onBack}><Ionicons name="arrow-back" size={22} color="#111820"/><Text style={s.backText}>Printers</Text></Pressable><Text style={s.help}>See your whole printer fleet at a glance.</Text></View><Pressable style={s.add} onPress={openNew}><Ionicons name="add" size={22} color="#FFF"/><Text style={s.addText}>Add printer</Text></Pressable></View>
    <View style={s.hero}><View><Text style={s.kicker}>PRINTER FLEET</Text><Text style={s.heroValue}>{counts.working} of {active} working</Text><Text style={s.heroHelp}>{counts.under_repair||counts.needs_attention?`${counts.under_repair+counts.needs_attention} need attention`:`${active} active printers ready`}</Text></View><View style={s.heroIcon}><Ionicons name="hardware-chip-outline" size={34} color="#00AE42"/></View></View>
    <View style={s.summary}>{STATUSES.slice(0,3).map(x=><View key={x.id} style={[s.summaryCard,{backgroundColor:x.soft}]}><Ionicons name={x.icon} size={20} color={x.color}/><Text style={[s.summaryNumber,{color:x.color}]}>{counts[x.id]}</Text><Text style={s.summaryLabel}>{x.short}</Text></View>)}</View>
    <View style={s.sectionHead}><Text style={s.sectionTitle}>All printers</Text><Text style={s.count}>{printers.length}</Text></View>
    {loading?<ActivityIndicator size="large" color="#00AE42"/>:printers.length?<View style={s.grid}>{printers.map(p=>{const st=statusInfo(p.status);return <Pressable key={p.id} style={[s.printerCard,{width:cardWidth}]} onPress={()=>openEdit(p)}><View style={s.cardTop}><View style={s.printerIcon}><Ionicons name="cube-outline" size={28} color="#111820"/></View><View style={[s.statusPill,{backgroundColor:st.soft}]}><View style={[s.dot,{backgroundColor:st.color}]}/><Text style={[s.statusText,{color:st.color}]}>{st.label}</Text></View></View><Text style={s.printerName}>{p.name}</Text><Text style={s.model}>{p.model}</Text>{p.notes?<Text style={s.printerNote} numberOfLines={2}>{p.notes}</Text>:<Text style={s.noNote}>No issue noted</Text>}<View style={s.cardFoot}><Text style={s.editText}>View or update</Text><Ionicons name="arrow-forward" size={18} color="#111820"/></View></Pressable>})}</View>:<View style={s.empty}><Ionicons name="hardware-chip-outline" size={38} color="#00AE42"/><Text style={s.emptyTitle}>Add your first printer</Text><Text style={s.help}>Name each machine so everyone knows which printer needs attention.</Text><Pressable style={s.emptyButton} onPress={openNew}><Text style={s.emptyButtonText}>Add printer</Text></Pressable></View>}
  </ScrollView>;
}

const s=StyleSheet.create({
  page:{paddingTop:12,paddingBottom:40},heading:{flexDirection:"row",alignItems:"center",gap:12},back:{minHeight:46,flexDirection:"row",alignItems:"center",gap:9},backText:{color:"#111820",fontSize:24,fontWeight:"700"},help:{marginTop:2,color:"#626A73",fontSize:14,lineHeight:20},add:{minHeight:46,paddingHorizontal:14,flexDirection:"row",alignItems:"center",gap:6,borderRadius:10,backgroundColor:"#111820"},addText:{color:"#FFF",fontSize:14,fontWeight:"700"},
  hero:{marginTop:18,padding:22,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderRadius:14,backgroundColor:"#111820"},kicker:{color:"#AAB3BB",fontSize:11,fontWeight:"700",letterSpacing:1.7},heroValue:{marginTop:6,color:"#FFF",fontSize:32,fontWeight:"700",letterSpacing:-.8},heroHelp:{marginTop:5,color:"#D5DBE0",fontSize:14},heroIcon:{width:62,height:62,alignItems:"center",justifyContent:"center",borderRadius:31,backgroundColor:"#20302A"},
  summary:{marginTop:10,flexDirection:"row",gap:8},summaryCard:{minWidth:0,flex:1,padding:12,borderRadius:11},summaryNumber:{marginTop:7,fontSize:24,fontWeight:"700"},summaryLabel:{marginTop:1,color:"#4F5861",fontSize:11,fontWeight:"600"},sectionHead:{marginTop:24,marginBottom:10,flexDirection:"row",alignItems:"center",gap:8},sectionTitle:{color:"#111820",fontSize:19,fontWeight:"700"},count:{minWidth:28,paddingVertical:4,textAlign:"center",overflow:"hidden",borderRadius:14,backgroundColor:"#F0F1F2",color:"#626A73",fontSize:12,fontWeight:"700"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},
  printerCard:{minHeight:214,padding:17,borderWidth:1,borderColor:"#E0E3E7",borderRadius:13,backgroundColor:"#FFF"},cardTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},printerIcon:{width:48,height:48,alignItems:"center",justifyContent:"center",borderRadius:10,backgroundColor:"#F3F4F5"},statusPill:{paddingHorizontal:9,paddingVertical:6,flexDirection:"row",alignItems:"center",gap:5,borderRadius:14},dot:{width:7,height:7,borderRadius:4},statusText:{fontSize:11,fontWeight:"700"},printerName:{marginTop:16,color:"#111820",fontSize:20,fontWeight:"700"},model:{marginTop:3,color:"#087A38",fontSize:14,fontWeight:"700"},printerNote:{marginTop:10,flex:1,color:"#626A73",fontSize:13,lineHeight:18},noNote:{marginTop:10,flex:1,color:"#90969C",fontSize:13},cardFoot:{minHeight:38,marginTop:10,paddingTop:10,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderTopWidth:1,borderTopColor:"#ECEEEF"},editText:{color:"#111820",fontSize:12,fontWeight:"700"},
  empty:{padding:32,alignItems:"center",borderWidth:1,borderColor:"#E0E3E7",borderRadius:13,backgroundColor:"#F7F8F8"},emptyTitle:{marginTop:11,color:"#111820",fontSize:20,fontWeight:"700"},emptyButton:{minHeight:44,marginTop:17,paddingHorizontal:18,alignItems:"center",justifyContent:"center",borderRadius:9,backgroundColor:"#111820"},emptyButtonText:{color:"#FFF",fontWeight:"700"},
  formCard:{width:"100%",maxWidth:680,alignSelf:"center",marginTop:10,padding:20,borderWidth:1,borderColor:"#E0E3E7",borderRadius:13,backgroundColor:"#FFF"},formTitle:{color:"#111820",fontSize:28,fontWeight:"700",letterSpacing:-.6},label:{marginTop:18,marginBottom:7,color:"#111820",fontSize:13,fontWeight:"700"},input:{minHeight:54,paddingHorizontal:14,borderWidth:1,borderColor:"#D9DDE0",borderRadius:10,color:"#111820",backgroundColor:"#FFF",fontSize:16},notes:{minHeight:105,paddingTop:14,textAlignVertical:"top"},wrap:{flexDirection:"row",flexWrap:"wrap",gap:7},choice:{minHeight:42,paddingHorizontal:13,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#D9DDE0",borderRadius:9,backgroundColor:"#FFF"},choiceOn:{borderColor:"#111820",backgroundColor:"#111820"},choiceText:{color:"#39434C",fontSize:13,fontWeight:"600"},choiceTextOn:{color:"#FFF"},statusChoices:{gap:7},statusChoice:{minHeight:50,paddingHorizontal:13,flexDirection:"row",alignItems:"center",gap:9,borderWidth:1.5,borderRadius:10},statusChoiceText:{flex:1,fontSize:14,fontWeight:"700"},save:{minHeight:56,marginTop:22,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,borderRadius:10,backgroundColor:"#111820"},saveText:{color:"#FFF",fontSize:16,fontWeight:"700"},remove:{minHeight:48,marginTop:8,alignItems:"center",justifyContent:"center"},removeText:{color:"#9B2C3F",fontSize:14,fontWeight:"700"},
});
