import { useEffect, useRef, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text, TextInput } from './AppTypography';
import { ExpenseDatePicker } from './ExpensesScreen';
import { supabase } from '../lib/supabase';
import { userNotice } from '../lib/userNotice';
import { peso } from '../lib/format';

type Variant={id:string;option_value:string;stock_units:number;selling_price_php:number|null};
type Product={id:string;name:string;selling_price_php:number|null;source_product_options:Variant[];source_product_images:{image_url:string}[]};
type Package={id:string;name:string;package_price_php:number;tier:string;reseller_package_items:{quantity:number;source_product_id:string;source_product_option_id:string|null;source_products:{name:string}|null;source_product_options:{option_value:string;stock_units:number}|null}[]};
type Line={id:string;productId:string;optionId:string;quantity:string};
const uuid=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return (c==='x'?r:(r&3)|8).toString(16);});
const today=()=>{const d=new Date();return `${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${d.getFullYear()}`;};
const iso=(text:string)=>{const m=text.match(/^(\d{2})-(\d{2})-(\d{4})$/);if(!m)return null;const value=`${m[3]}-${m[2]}-${m[1]}`;const d=new Date(`${value}T12:00:00`);return !Number.isNaN(d.getTime())&&d.getDate()===Number(m[1])&&d.getMonth()+1===Number(m[2])?value:null;};

export function ResellerPackageCheckout({businessId,locationId,immediate=false,onCancel,onSaved}:{businessId:string;locationId:string;immediate?:boolean;onCancel:()=>void;onSaved:()=>void}){
 const [products,setProducts]=useState<Product[]>([]),[packages,setPackages]=useState<Package[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [type,setType]=useState<'set'|'custom'>('set'),[packageId,setPackageId]=useState(''),[lines,setLines]=useState<Line[]>([]),[quantity,setQuantity]=useState('1'),[total,setTotal]=useState('');
 const [customer,setCustomer]=useState(immediate?'Walk-in customer':''),[contact,setContact]=useState(''),[address,setAddress]=useState(''),[remarks,setRemarks]=useState(''),[date,setDate]=useState(today),[method,setMethod]=useState('cash'),[busy,setBusy]=useState(false);
 const [stocks,setStocks]=useState<{source_product_id:string;source_product_option_id:string|null;on_hand:number;reserved:number}[]>([]);
 useEffect(()=>{let alive=true;void supabase.from('reseller_stock_summary').select('source_product_id,source_product_option_id,on_hand,reserved').eq('business_id',businessId).eq('location_id',locationId).then(({data,error})=>{if(!alive)return;if(error)setError(error.message);else setStocks(data??[]);});return()=>{alive=false};},[businessId,locationId]);
 const request=useRef(uuid()),busyRef=useRef(false);
 useEffect(()=>{let alive=true;void(async()=>{try{const [a,b]=await Promise.all([supabase.from('source_products').select('id,name,selling_price_php,source_product_options(id,option_value,stock_units,selling_price_php),source_product_images(image_url)').eq('business_id',businessId).eq('status','active').order('name'),supabase.from('reseller_packages').select('id,name,tier,package_price_php,reseller_package_items(source_product_id,source_product_option_id,quantity,source_products(name),source_product_options(option_value,stock_units))').eq('business_id',businessId).eq('active',true).order('name')]);if(a.error)throw a.error;if(b.error)throw b.error;if(alive){setProducts((a.data??[]) as Product[]);setPackages((b.data??[]) as unknown as Package[]);}}catch(e){if(alive)setError((e as Error).message);}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[businessId]);
 const chosen=packages.find(p=>p.id===packageId);
 const change=(id:string,key:keyof Line,value:string)=>setLines(rows=>rows.map(row=>row.id===id?{...row,[key]:value}:row));
 const contents=lines.map(line=>{const p=products.find(p=>p.id===line.productId),v=p?.source_product_options.find(v=>v.id===line.optionId);return {line,p,v,pieces:Number(line.quantity)*(v?.stock_units??1)};});
 const suggested=contents.reduce((sum,row)=>sum+Number(row.v?.selling_price_php??row.p?.selling_price_php??0)*Number(row.line.quantity),0)*Number(quantity);
 const totalPieces=type==='set'?(chosen?.reseller_package_items??[]).reduce((sum,line)=>sum+line.quantity*(line.source_product_options?.stock_units??1),0)*Number(quantity):contents.reduce((sum,row)=>sum+row.pieces,0)*Number(quantity);
 const needs=new Map<string,{name:string;pieces:number;available:number}>();
 const addNeed=(p:string,v:string|null,name:string,pieces:number)=>{const key=p+':'+(v??'');const stock=stocks.find(s=>s.source_product_id===p&&s.source_product_option_id===(v||null));const prev=needs.get(key);needs.set(key,{name,pieces:(prev?.pieces??0)+pieces,available:Math.max(0,Number(stock?.on_hand??0)-Number(stock?.reserved??0))});};
 if(type==='set')chosen?.reseller_package_items.forEach(line=>addNeed(line.source_product_id,line.source_product_option_id,(line.source_products?.name??'Product')+' · '+(line.source_product_options?.option_value??''),line.quantity*(line.source_product_options?.stock_units??1)*Number(quantity)));
 else contents.forEach(row=>{if(row.p&&(!row.p.source_product_options.length||row.v))addNeed(row.p.id,row.v?.id??null,row.p.name+' · '+(row.v?.option_value??''),row.pieces*Number(quantity));});
 const shortages=[...needs.values()].filter(row=>row.pieces>row.available);
 const save=async()=>{if(busyRef.current)return;const q=Number(quantity),price=Number(total),paymentDate=iso(date);
  if(!customer.trim()||!Number.isInteger(q)||q<=0||!Number.isFinite(price)||price<=0)return userNotice('Complete the order','Enter a customer name, whole package quantity and full price greater than zero.');
  if(type==='set'&&!chosen)return userNotice('Choose a set package');
  if(type==='custom'&&(!lines.length||contents.some(row=>!row.p||(row.p.source_product_options.length&&!row.v)||!Number.isInteger(Number(row.line.quantity))||Number(row.line.quantity)<=0)))return userNotice('Complete the custom package','Choose the exact variant and a positive whole quantity for every item.');
  if(immediate&&shortages.length)return userNotice('Stock needed first','Save this as a customer pre-order instead. Buy or print the missing pieces before handing it over.');
  if(immediate&&!paymentDate)return userNotice('Choose the payment date');
  busyRef.current=true;setBusy(true);try{const {error}=await supabase.rpc('create_reseller_package_order',{b:businessId,l:locationId,request:request.current,package:type==='set'?packageId:null,contents:type==='custom'?lines.map(line=>({product_id:line.productId,option_id:line.optionId||null,quantity:Number(line.quantity)})):[],customer:customer.trim(),contact:contact.trim(),address:address.trim(),quantity:q,total:price,paid_now:immediate,payment_day:immediate?paymentDate:null,method,remarks:remarks.trim()});if(error)throw error;userNotice(immediate?'Package sold':'Pre-order saved',immediate?'The payment is recorded once and all included pieces have been deducted.':'Record the 50% deposit in Pre-orders to reserve the included pieces.');onSaved();}catch(e){userNotice('Not saved',(e as Error).message);}finally{busyRef.current=false;setBusy(false);}
 };
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Button label="← Back" onPress={onCancel} secondary/><Text style={s.title}>{immediate?'Sell a reseller package':'New customer pre-order'}</Text><Text style={s.help}>{immediate?'For a fully paid package handed to the customer now.':'Choose a set package or build a custom one. Its contents are saved with this order.'}</Text>{error?<Text style={s.error}>{error}</Text>:null}{loading?<Text style={s.help}>Loading products…</Text>:<>
  <View style={s.buttons}><Button label="Set package" secondary={type!=='set'} onPress={()=>setType('set')}/><Button label="Custom package" secondary={type!=='custom'} onPress={()=>setType('custom')}/></View>
  {type==='set'?<>{!packages.length?<Text style={s.help}>No set packages yet. Create one under Products → Manage set packages, or choose Custom package.</Text>:packages.map(p=><Pressable key={p.id} accessibilityRole="button" style={[s.card,p.id===packageId&&s.selected]} onPress={()=>{setPackageId(p.id);setTotal(String(Number(p.package_price_php)*Number(quantity)));}}><Text style={s.heading}>{p.name} · {peso(Number(p.package_price_php))}</Text><Text style={s.help}>{p.tier}</Text>{p.reseller_package_items.map((line,index)=><Text key={index} style={s.help}>{line.quantity} × {line.source_products?.name} {line.source_product_options?.option_value??''} · {line.quantity*(line.source_product_options?.stock_units??1)} pieces</Text>)}</Pressable>)}</>:<><Text style={s.heading}>Add products to this package</Text><View style={s.buttons}>{products.map(p=><Button key={p.id} label={`+ ${p.name}`} secondary onPress={()=>setLines(rows=>[...rows,{id:uuid(),productId:p.id,optionId:'',quantity:'1'}])}/>)}</View>{contents.map(({line,p,v,pieces})=><View key={line.id} style={s.card}><View style={s.row}>{p?.source_product_images[0]?.image_url?<Image source={{uri:p.source_product_images[0].image_url}} style={s.photo} resizeMode="contain"/>:null}<Text style={s.heading}>{p?.name}</Text></View><View style={s.buttons}>{p?.source_product_options.map(option=><Button key={option.id} label={option.option_value} secondary={option.id!==line.optionId} onPress={()=>change(line.id,'optionId',option.id)}/>)}</View><Field label={`Selections · ${v?.stock_units??1} pieces each`} value={line.quantity} onChange={value=>change(line.id,'quantity',value)} numeric/><Text style={s.help}>{pieces} pieces in one custom package</Text><Button label="Remove item" secondary onPress={()=>setLines(rows=>rows.filter(row=>row.id!==line.id))}/></View>)}{suggested>0?<Button label={`Use product prices · ${peso(suggested)}`} secondary onPress={()=>setTotal(String(suggested))}/>:null}</>}
  <Field label="Number of packages · Required" value={quantity} onChange={value=>{setQuantity(value);if(type==='set'&&chosen)setTotal(String(Number(chosen.package_price_php)*Number(value)));}} numeric/>
  <Field label="Full price for this entire order · PHP · Required" value={total} onChange={setTotal} numeric/>
  <Text style={s.help}>{totalPieces||0} individual pieces in total{!immediate?` · Deposit required: ${peso(Number(total)*0.5)}`:''}</Text>
  {[...needs.values()].map(row=><Text key={row.name} style={row.pieces>row.available?s.error:s.help}>{row.name}: {row.available} available · {row.pieces} needed{row.pieces>row.available?` · Need to order: ${row.pieces-row.available} pieces`:''}</Text>)}
  {shortages.length?<Text style={s.error}>{immediate?'Not enough stock to hand over now. Use customer pre-orders.':'You can save this pre-order. Buy or print the missing pieces before shipping.'}</Text>:null}
  <Field label="Customer name · Required" value={customer} onChange={setCustomer}/>
  {!immediate?<><Field label="Contact · Optional" value={contact} onChange={setContact}/><Field label="Delivery address · Can be added later" value={address} onChange={setAddress}/></>:<><ExpenseDatePicker label="Payment date · Required" value={date} onChange={setDate}/><View style={s.buttons}>{['cash','gcash','bank','other'].map(m=><Button key={m} label={m==='gcash'?'GCash':m[0].toUpperCase()+m.slice(1)} secondary={method!==m} onPress={()=>setMethod(m)}/>)}</View></>}
  <Field label="Remarks · Optional" value={remarks} onChange={setRemarks}/><Text style={s.help}>{immediate?'Stock is deducted when you confirm. Do not enter this payment again under Pre-orders.':'No payment is assumed. Stock is reserved after the deposit is recorded and deducted when shipped.'}</Text><Button label={busy?'Saving…':immediate?'Confirm package sale':'Save pre-order'} disabled={busy||!!error} onPress={()=>void save()}/>
 </>}</ScrollView>;
}
function Field({label,value,onChange,numeric=false}:{label:string;value:string;onChange:(v:string)=>void;numeric?:boolean}){return <View style={{gap:7}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={s.input} value={value} onChangeText={onChange} keyboardType={numeric?'decimal-pad':'default'}/></View>;}
function Button({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,disabled&&{opacity:.5}]}><Text style={[s.buttonText,secondary&&{color:'#315FBE'}]}>{label}</Text></Pressable>;}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1080,alignSelf:'center',padding:18,paddingBottom:90,gap:14},title:{fontSize:26,fontWeight:'700',color:'#151924'},heading:{fontSize:17,fontWeight:'700',color:'#151924'},label:{fontSize:14,fontWeight:'600',color:'#343A47'},help:{fontSize:14,lineHeight:21,color:'#626A78'},error:{fontSize:14,color:'#8A2943'},card:{borderWidth:1,borderColor:'#E0E3EA',borderRadius:14,padding:15,gap:10,backgroundColor:'white'},selected:{borderColor:'#315FBE',backgroundColor:'#EDF3FB'},buttons:{flexDirection:'row',flexWrap:'wrap',gap:9},row:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:10},photo:{width:76,height:76},input:{minHeight:48,borderWidth:1,borderColor:'#D9DDE5',borderRadius:10,padding:12,fontSize:16,color:'#151924',backgroundColor:'white'},button:{minHeight:44,paddingHorizontal:15,paddingVertical:11,backgroundColor:'#315FBE',borderRadius:10,alignItems:'center',justifyContent:'center'},secondary:{backgroundColor:'#EDF3FB',borderWidth:1,borderColor:'#CFDAEB'},buttonText:{fontSize:14,fontWeight:'600',color:'white'}});
